### ISSUE TITLE
BUG: Can't delete some commons

### ISSUE THREAD

**Issue by albertyu03** [ucsb-cs156-s23/proj-happycows-s23-6pm-1#41]
Recreation:

- Create some commons
- set date to current, set starting balance to 1, set cow price to 2, tick show leaderboard, degradation rate = 1, carry capacity = 100
- join commons
- set balance to 5
- try to delete

Likely is a result of joining the commons and attempting to delete after (db issue?)

**Comment by GlassBricks** [comment]
Should be fixed by #46
